### ISSUE TITLE
SteperLayout#onComplete does not respect BlockingStep flow

### ISSUE THREAD

**Issue by FWStelian** [stepstone-tech/android-material-stepper#83] opened 2017-03-09 18:42 UTC
What I'm trying to do : 
-  create several steps to collect info from user
-  upload all user info using a BlockingStep when the user taps "Complete" (on the last step)

The problem : 
- `onNextClicked()` method is not being called in the last step  

Cause: 
- `StepperLayout#onComplete()` does not check for BlockingSteps

**Comment by zawadz88** [comment] 2017-03-09 19:10
Hi,
This looks like a duplicate of #52.
Please see the answer in that issue and let me know if it makes sense to you.

**Comment by FWStelian** [comment] 2017-03-10 11:07
@zawadz88  I had a look at #52  comments and answers. 

I agree with you that, technically, there is no "next" step to go to.  I also took notice of the 2 workarounds presented  (adding extra step to achieve desired functionality and handling `onComplete()` event from `StepperListener` ). 

The activity is already handling `onComplete()` but it is doing something different that what the last fragment is intended for and I don't want to "leak" the information from the fragment to the activity  (multiple reasons can be given).

I am aware that you can workaround this issue, and that in general, you would probably use the activity to aggregate all the information from the steps but I think it is a problem that the library breaks the user expectation : you expect a blocking step to function the same way regardless of it's position in the adapter.  Maybe the docs could explain better this caveat or, maybe, add a new type of step `CompleteBlockingStep`  with a new callback that will allow the desired behaviour. 

Awesome library  BTW, thanks :)

**Comment by zawadz88** [comment] 2017-03-10 15:58
Hi @FWStelian,

> you expect a blocking step to function the same way regardless of it's position in the adapter. 

You raise a good point here. I agree that a new callback seems reasonable in this situation - I think it might actually be a part of `BlockingStep`. 
I'm pretty preoccupied at the moment so I don't know when the next release might happen, however I'm happy to review any PR regarding this for the time being :)

And thanks for the thorough feedback!

**Comment by poltographer6** [comment] 2017-03-12 03:39
I have a question too about BlockingStep, how can I enable the Complete Button here?
![screenshot_1489289948](https://cloud.githubusercontent.com/assets/26056672/23828810/9264b56e-0718-11e7-8e9d-c86c832cab7e.png)

**Comment by FWStelian** [comment] 2017-03-12 10:43
@poltographer6  you probably set stepperLayout#.setNextButtonVerificationFailed(true) from your activity.

**Comment by poltographer6** [comment] 2017-03-12 11:15
@FWStelian  no I didn't. Here's my code

`public class UploadApp extends AppCompatActivity  implements StepperLayout.StepperListener {
    
        private StepperLayout mStepperLayout;
        Toolbar uploadAppToolbar;
        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_upload_app);
    
            uploadAppToolbar = (Toolbar) findViewById(R.id.uploadAppToolbar);
            uploadAppToolbar.setTitle("Application Upload");
    
            mStepperLayout = (StepperLayout) findViewById(R.id.stepperLayout);
            mStepperLayout.setAdapter(new UploadAppStepperAdapter(getSupportFragmentManager(), this));
    
        }
    
        @Override
        public void onCompleted(View completeButton) {
    
            System.out.println("Test");
    
    
    
        }
    
        @Override
        public void onError(VerificationError verificationError) {
    
    
        }
    
        @Override
        public void onStepSelected(int newStepPosition) {
    
        }
    
        @Override
        public void onReturn() {
    
        }


    }`

**Comment by poltographer6** [comment] 2017-03-12 11:23
Nothing happened when I click Complete Button, it should print "Test". Can you help me what's wrong with my code? I used BlockingStep to my Steps

**Comment by FWStelian** [comment] 2017-03-12 12:48
@zawadz88  PR created

**Comment by zawadz88** [comment] 2017-03-13 14:07
@FWStelian thanks for your helped! #87 was merged. I'll release a new version of the library soon and it should be available from JCenter.

**Closed by zawadz88** 2017-03-13 14:07 UTC
Labels: help wanted
